### ISSUE TITLE
[EPIC] Unified web experience Phase 2

### ISSUE THREAD

**Issue by dhmlau** [strongloop/v4.loopback.io#64]
## Description / Steps to reproduce / Feature proposal
To complete the work for unified web experience, the goal is to have loopback.io shows the content of v4.loopback.io

## Things to consider/discuss
In the current loopback.io, there are getting-started, examples, resources pages that are specific to the older version of LoopBack.  Are we going to remove them or keep them, something like:
```
loopback.io/getting-started -> loopback.io/lb3/getting-started
loopback.io/resources -> loopback.io/lb3/resources
```

## What needs to be done
- [ ] make the existing docs work in the new framework/structure
     - [ ] copy the existing docs https://loopback.io/doc/ to v4.loopback.io
     - [ ] make the docs pages work with a static site generator, e.g. VuePress
         - some initial work has been done in this PR https://github.com/strongloop/v4.loopback.io/pull/45 
- [ ] decide on what to do with the existing loopback.io content (see above)
- [ ] switch v4.loopback.io github pages to be served on loopback.io  (is it an easy switch?)

@strongloop/loopback-maintainers, thoughts?

**Comment by bajtos** [comment]
IMO, it's better to preserve the LB3 version of both pages `getting-started` and `resources`.

**Comment by dhmlau** [comment]
> IMO, it's better to preserve the LB3 version of both pages getting-started and resources.

@raymondfeng has expressed the same viewpoint.

**Comment by dhmlau** [comment]
Closing as done.
